import logging

logging.error("Error occured")